### ISSUE TITLE
[App] : [Saber] : Player Scripts

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#158]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

Going to make a quick Unity data manager that will handle the storage of different variables, 

* * * 
Update: 11/4/2023

- I will start with the `PlayerData.cs`, which you can add to any Scene by attaching it to any empty GameObject! 
The objective of this script will be to handle the Player Saving/Loading within the whole game. 

I will try to include any additional functionality and extensions to it as well.

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

For the time being, the data manager will have the basics, like playerName, player score with 0, ect..

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

Nothing as of right now.

* * *

**Additional information**
Add any other context or examples of this concept here.

If there is anything additional to add, I will edit and place it here.

**Comment by h0lybyte** [comment]
Here is the current PlayerData that is being utilized by the PlayerDataManager as of 11/1/2023

```c#
public class PlayerData
{
    public int level;
    public int health;
    public float[] position = new float[2];

    public PlayerData()
    {
        level = 1;
        health = 100;
        position[0] = 0;
        position[1] = 0;
    }
}
```
I will try to keep this up to date but the class is inside of the PlayerDataManager.cs , so it is easy to keep track of.

**Comment by h0lybyte** [comment]
I will reopen this to get more feedback / suggestions to how we want to handle the data.

**Comment by 1954764916** [comment]
If you feel that the basic components are not enough, Just use ScriptableObject components .It can be 
to **### serialize and deserialize** storage resources, we can also use **a dictionary or a collection List** to store data.


for example：
private void CreatInstance()
{
	 Data data = ScriptableObject.CreateInstance<Data>();
	 data.name ="jack";
	 data.age =18;    
	 AssetDatabase.CreateAsset(data, "Assets/Resources/DB/" + data.name + ".asset");
	 Resources.UnloadAsset(data);
	 AssetDatabase.Refresh();
}

**Comment by h0lybyte** [comment]
> If you feel that the basic components are not enough, Just use ScriptableObject components .It can be to **### serialize and deserialize** storage resources, we can also use **a dictionary or a collection List** to store data.
> 
> for example： private void CreatInstance() { Data data = ScriptableObject.CreateInstance(); data.name ="jack"; data.age =18; AssetDatabase.CreateAsset(data, "Assets/Resources/DB/" + data.name + ".asset"); Resources.UnloadAsset(data); AssetDatabase.Refresh(); }

I believe the issue with going down this route is that it might not work with a WebGL build, the only storage that we end up having is their cookie / localStorage.

Of course the other route would be to store the data onto a remote server.

**Comment by 1954764916** [comment]
Someone has used DevOps. The United States can provide free 50G. This can save our basic data. We use AssetBundle to load remotely. WebGL can support AssetBundle very well.

**Comment by h0lybyte** [comment]
Do we want to add "Life" to our game? So that if you die aka go under your current health, you will lose a life. 

I suppose we could implement that later on during the build process.

**Comment by h0lybyte** [comment]
The `Player.cs` will be a singleton instance that represents the player as a whole.

With `PlayerCombat.cs` being the script that handles the combat? Hmm, I can see why combat could just be its own instance too, hmm.
