### ISSUE TITLE
[App] : [Saber] : GameObject Pooling for Scaling Optimization

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#159]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

Going to build a quick game object pool that will have some general optimizations for loading Unity's game objects. 
We can extend it out for NPCs, tiles, ect.. depending on the game's core theme.

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

The pool will help organize the entities that the game engine will be rendering, allowing us to scale without abusing the CPU.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?
- [Unity Tutorial on Object Pooling](https://learn.unity.com/tutorial/introduction-to-object-pooling)

* * *

**Additional information**
Add any other context or examples of this concept here.

Any additional information can be provided as I build out the pool.

**Comment by BChip** [comment]
I have implemented object pooling in a game i made a long time ago in XNA. It helps, but looking at Unity; there is more there to help. You can use a particle system, Unity DOTS (burst, jobs, ecs), RenderMeshInstanced, DrawMeshInstancedIndirect

Here is a video example:  https://www.youtube.com/watch?v=6mNj3M1il_c

Here is a good example of burst: https://www.youtube.com/watch?v=cJEmmvDQx5M

**Comment by BChip** [comment]
Oh it looks like Unity has an official ECS system too kind of like Bevy

**Comment by h0lybyte** [comment]
Ah snap, I am reading up on this issue right now. https://forum.unity.com/threads/webgl-and-dots.1417806/

Hopefully we do not run into problems if we use DOTS/ECS?

**Comment by 1954764916** [comment]
We can use Unity's pooling technology. For example, our dragon fires bullets and the sound of his footsteps has already been run on this technology. In general, if you repeatedly create and destroy something, you will use it. Prevent excessive GC generation.

**Comment by h0lybyte** [comment]
The first object we can add into the GameObject pool could be the Rune Obelisks and maybe a pool for blank NPCs .

- Rune Obelisks 
- NPCs as `Cards`, similar to how Paper Mario handles it.

**Comment by h0lybyte** [comment]
I started to handle the NPCs in this issue ticket -> https://github.com/KBVE/kbve/issues/212

I was debating if I wanted to create a general pool and then extend it out for the NPC Pooling but honestly, I think it might make more sense to isolate the Pools into their own respective instances. 

So instead of having an overarching pool that handles the different NPCs, Spells, objects, ect.. We split the pools up for the general scope that they represent. One pool for the NPCs, one pool for ambient environmental objects, ect...

**Comment by h0lybyte** [comment]
Closing this out as it is part of the Entity GameObject pool.
