### ISSUE TITLE
[App] : [Saber] : Audio Busses

### ISSUE THREAD

**Issue by taylorbrook** [KBVE/kbve#163]
**Core Concept/Theory**
I propose a shared audio bus system to use throughout the project:
- UI
- SFX
- Dialogue
- Music

All feeding into the master bus and set by default to -3db

Other busses may be needed for specific in-game audio effects processing, but they could all feed into one of these busses above and their levels made accessible to the player in the menu.

* * *

**Comment by pablowunderlich** [comment]
Hello, helping out with the audio, be it SFX, music, or implementation.

**Comment by pablowunderlich** [comment]
I have scripted audio systems into Unity, spawning objects and sounds and managing music. Also created a footsteps manager. Could record sounds, create music, or just do implementation

**Comment by wizcats** [comment]
Hello, I'm here to help with the music (:

**Comment by pablowunderlich** [comment]
That sounds great. Let's coordinate. I'm ok for you to take on the music. I can do SFX and implementaion

**Comment by h0lybyte** [comment]
There are some limitations to the Audio within the scope of WebGL.
The [main documentation](https://docs.unity3d.com/2022.3/Documentation/Manual/webgl-audio.html) states that it **does NOT support FMOD.** :C

**Comment by 1954764916** [comment]
I hope to use wav format for the audio format. If MP3 is used, compression will be lost. Audio in wav format takes up more memory.

**Comment by taylorbrook** [comment]
my preference is mono wav for sfx and high quality stereo ogg for music. wav for music will make for too big of file sizes, I fear, and ogg can still loop seamlessly.

**Comment by 1954764916** [comment]
> my preference is mono wav for sfx and high quality stereo ogg for music. wav for music will make for too big of file sizes, I fear, and ogg can still loop seamlessly.


It is best not to use Ogg format, wav format has the best sound effect

**Comment by taylorbrook** [comment]
@h0lybyte - any opinion on format? see discussion of wav vs mp3 vs ogg above

**Comment by pablowunderlich** [comment]
> @h0lybyte - any opinion on format? see discussion of wav vs mp3 vs ogg above

I recall h0lybyte mentioned OGG since it's a WebGL build. Wav might be too heavy.

**Comment by taylorbrook** [comment]
"How many audio folks are we? How do y'all wanna split the work?"
- this is a good question! I'm happy to play a support role if you want to take the lead. It sound like you have good experience on the technical audio side (implementing in engine). I can provide sfx, music, and implement as needed. Another option would be that one of us takes music, another SFX, and another technical audio. Let me know your thoughts!

**Comment by h0lybyte** [comment]
Using OGG/MP3 would be the best move in terms of compression, as to save some of the file size. We can get away with using WAV if its a major piece of the level, so maybe limited to just a couple (1-3) WAVs per level that represents the background music?

**Comment by pablowunderlich** [comment]
I’ll happily take technical audio. Let’s create a discord chat amongst us. Please add me to discord: pablowunderlich

**Comment by vascuin** [comment]
Hey guys, I'm here also to help with sound.

**Comment by vascuin** [comment]
I'm confortable with music, sfx and mixing
I know very little about implementation thro FMOD

**Comment by pablowunderlich** [comment]
> I'm confortable with music, sfx and mixing
> 
> I know very little about implementation thro FMOD 

We won't be using FMOD or wwise due to this being a WebGL. I'll be taking care of most of the implementation within Unity. Please join the audio group in Discord to coordinate.

**Comment by 1954764916** [comment]
> Using OGG/MP3 would be the best move in terms of compression, as to save some of the file size. We can get away with using WAV if its a major piece of the level, so maybe limited to just a couple (1-3) WAVs per level that represents the background music?

I very much agree with your point of view. The background music of a scene is only one and, I guess 30 seconds is about the same. If the 3D scene is not very large, the sound effects of other strike actions are very short, 1-3 seconds, so that it does not occupy memory. , if we want to create a large scene, then switch to MP3, and finally consider using ogg format sound effects

**Comment by 1954764916** [comment]
Officially, webgl does not support Wwise, so that probably won’t work unless we can write the SDK ourselves, but we don’t have so much time.   
My major is not music, so I can only give a very unprofessional idea, using Corel VideoStudio 2024 to adjust the tone of the film.
Let the produced sound effects fade in and out, otherwise the scene transition will be strange.

**Comment by taylorbrook** [comment]
Anyone working on audio, please join this discord server: https://discord.gg/ENTz9EVT

**Comment by h0lybyte** [comment]
We could continue to use this ticket but I think it might make more sense to create a new issue ticket regarding audio.

**Comment by h0lybyte** [comment]
Going to close this out and move the conversation over to https://github.com/KBVE/kbve/issues/344
