### ISSUE TITLE
[App] : [Saber] : [Model] Dragon/Main Character

### ISSUE THREAD

**Issue by ZombehCorp** [KBVE/kbve#164]
**Core Concept/Theory**
Spyro style dragon character for use as the main player character.  Low polygon, with simple texturing/flat shading.

**Animation of the model in-game is done by taking the input value float and setting it to the animator_controller float that corresponds to the blend tree in the animator.  IE - Idle Walk float for transition between idle and walk.**

Work in Progress screenshot of current Dragon character.

![Dragon_WIP](https://github.com/KBVE/kbve/assets/144863694/d8784279-55a5-4127-b075-bbb698012909)

* * *

**Alternative Ideas**
Recolored version can be used for additional dragon characters.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

* * *

**Additional information**
Add any other context or examples of this concept here.

**Comment by h0lybyte** [comment]
The base model is done, so going to close this out.
