### ISSUE TITLE
[App] : [Saber] : SceneLoader.cs - Management, Transitions and Saving.

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#166]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

The scene manager will help us move between the different scenes, levels ect... 

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

It will help us switch faster among the scenes, we could also add a cute loading screen as well.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

No major references as of right now.

* * *

**Additional information**
Add any other context or examples of this concept here.

I will add any additional information.

**Comment by sjuhyeon** [comment]
```cs
using UnityEngine;
using UnityEngine.SceneManagement;

public class SceneManage : MonoBehaviour
{
    // Reference to loading screen ui element
    public GameObject loadingScreen;
    
    public void LoadScene(string sceneName)
    {
        if(loadingScreen != null)
        {
            loadingScreen.SetActive(true);
        }
        
        // start a coroutine to load the scene asynchronously
        StartCoroutine(LoadSceneAsync(sceneName));
    }
    
    private IEnumerator LoadSceneAsync(string sceneName)
    {
        AsyncOperation operation = SceneManager.LoadSceneAsync(sceneName);
        
        while(!operation.isDone)
        {
            // Can update progress bar, or any other loading screen stuff here
            // float t = Mathf.Clamp01(operation.progress / 0.9f);
            yield return null;
        }
        
        if(loadinScreen != null)
        {
            // Deactivate loading screen when scene is loaded
            loadingScreen.SetActive(false);
        }
    } 
}
```

**Comment by h0lybyte** [comment]
I am currently working on the SceneManager through this file:

https://github.com/KBVE/kbve/blob/main/apps/saber/Assets/Scripts/SceneLoader.cs

So let me rename this from SceneManager to SceneLoader too.

**Comment by h0lybyte** [comment]
This can be closed out for a GameManager.cs , which is part of the Entity System. 

Issue: https://github.com/KBVE/kbve/issues/212
