### ISSUE TITLE
[App] : [Saber] : Scene1 - Forest Biome

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#183]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

This issue ticket is in relation to the first scene game scene, where we would introduce the dragon, forest biome, etc..

The current issue is the water shader not rendering in WebGL, but it looks like Jack was able to resolve it. Furthermore, we also need to decrease the amount of objects that are being rendered within the WebGL build.

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

We will mainly use this `Scene1` to work on the game mechanics and introduce the general vibe of the game/environment.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

No major alternatives/examples as of right now.

* * *

**Additional information**
Add any other context or examples of this concept here.

I can update this ticket with any additional information.

**Comment by h0lybyte** [comment]
Going to rename the `Test` scene to `Scene1` and then update the Play button so that we can load the scenes dynamically? 
Hmm, let me see what I can update for now.

**Comment by h0lybyte** [comment]
Thanks to Jack Z for the water bug reference / solution.

Now I am looking to resolve a couple more bugs when loading the `Scene1`. 

Post Processing issues:

- 2 Warnings of `The referenced script (Unknown) on this Behaviour is missing!`
- `The tree PT_Pine_Tree_03_stump must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.` - I believe the LOD was missing on a couple of the stumps, I will go through and add them in.

**Comment by h0lybyte** [comment]
Okay I added a UIPlayerMenu.cs that has a default menu that renders over the game, currently it just renders two placeholder buttons. 

Button 1 / Button 2.

**Comment by 1954764916** [comment]
> Thanks to Jack Z for the water bug reference / solution.
> 
> Now I am looking to resolve a couple more bugs when loading the `Scene1`.
> 
> Post Processing issues:
> 
> * 2 Warnings of `The referenced script (Unknown) on this Behaviour is missing!`
> * `The tree PT_Pine_Tree_03_stump must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.` - I believe the LOD was missing on a couple of the stumps, I will go through and add them in.

The post-processing components were lost. I felt that the scene was already very beautiful, so I just deleted the missing components. If you want to add some light halo and fog, you can use this post-processing component, but I think It comes with native Fog, which has been checked in LightingSetting.

**Comment by 1954764916** [comment]
> Okay I added a UIPlayerMenu.cs that has a default menu that renders over the game, currently it just renders two placeholder buttons.

I haven't thought about the code to control the character player yet. The character control system downloaded from the official website is not very easy to use. I will change it when the model is finished later... I am thinking whether to let the dragon fly or let the dragon fly. Walk on the ground...

**Comment by h0lybyte** [comment]
A good part of the initial game design will be very similar to Mario 64, with this Scene represents the Castle / Tall Tall mountain scene, as such, I will try to include tributes and references to it in the distant background. We were thinking of adding those Rune Obelisks as isolated game objects that can be activated upon interaction, creating a similar structure as the Mario 64 Painting or Portals from WoW.  I am including this here because on the Scene1, I will add at least 3-5 initially within the fenced garden taking everyone to various Scene2 <-> Scene6.  Later on I will move the Obelisks into the continuous / endless mountain, hopefully they help continue to create that `endless` effect without boring the player.

**Comment by 1954764916** [comment]
> A good part of the initial game design will be very similar to Mario 64, with this Scene represents the Castle / Tall Tall mountain scene, as such, I will try to include tributes and references to it in the distant background. We were thinking of adding those Rune Obelisks as isolated game objects that can be activated upon interaction, creating a similar structure as the Mario 64 Painting or Portals from WoW. I am including this here because on the Scene1, I will add at least 3-5 initially within the fenced garden taking everyone to various Scene2 <-> Scene6. Later on I will move the Obelisks into the continuous / endless mountain, hopefully they help continue to create that `endless` effect without boring the player.


Sounds fun, awesome

**Comment by h0lybyte** [comment]
I recently changed the Forest Biome for Scene1 , I am still trying to get a hang of the terrain management but I feel like it can be done via C# rather than the editor. Since the editor basically builds a static terrain, which I think will be fine for some main areas , like camps, towns, ect.. but I do think we should extend it out and try to build an abstract forest that generates via a seed.

**Comment by h0lybyte** [comment]
This scene for the Forest Biome has been resolved.

The only major issues are layers  + navmesh generation, also lighting but these can be resolved later on.
