### ISSUE TITLE
[App] : [Saber] : Scene3 - Chippi

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#205]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

This will be Scene 3 of the Game. 
I will let Chippi take the directive of where this Scene would go. 

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

We can talk about it here.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

Definitely need some examples of how it would look.

* * *

**Additional information**
Add any other context or examples of this concept here.

Place any concepts here that might help!

**Comment by BChip** [comment]
I am working on this

**Comment by h0lybyte** [comment]
We can close this out as well!
