### ISSUE TITLE
[App] : [Saber] : Scene2 - Sjuhyeon

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#206]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

Scene2 is currently being worked on by Sjuhyeon! 

I will ask him to place information / notes on this issue ticket.

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

* * *

**Additional information**
Add any other context or examples of this concept here.

**Comment by h0lybyte** [comment]
Do you have some NPC ideas that you would like to have in the map? 

While I am working on the Ghost, I could add a couple other NPCs for the map. 

I actually think the Portal that you take back to Scene1 would be a great idea, it might be a prefab that I could create as well.

**Comment by sjuhyeon** [comment]
> Do you have some NPC ideas that you would like to have in the map?
> 
> While I am working on the Ghost, I could add a couple other NPCs for the map.
> 
> I actually think the Portal that you take back to Scene1 would be a great idea, it might be a prefab that I could create as well.

Yes, maybe we can add something similar below which can attack with venom
![image](https://github.com/KBVE/kbve/assets/38283518/b13e69f5-2870-4570-9493-4191ea28f34e)

Again something similiar below which can throw sharp ice pieces
![image](https://github.com/KBVE/kbve/assets/38283518/5660d971-eef2-4cde-bd1e-d31a2369d00b)

**Comment by h0lybyte** [comment]
![octopus_evil](https://github.com/KBVE/kbve/assets/5599058/46d0be7f-cc99-4582-834b-0054e0bdbf5b)

This could be an example of the Octopus and I did make a quick one for the Wolf but it was a bit too cute and not evil enough xD

![cute_wolf](https://github.com/KBVE/kbve/assets/5599058/d83bd470-9d1b-4251-b224-f897afd39927)

**Comment by 1954764916** [comment]
a bit too cute ...
kids will definitely love it

**Comment by sjuhyeon** [comment]
Octopus looks fine. We can use Frog instead of Wolf so it can attack with his poison

**Comment by h0lybyte** [comment]
Going to close this ticket out for now.
