### ISSUE TITLE
[MUSIC] : Wolfgang Lohr & Offbeat - Swing in Spring (Glenn Gatsby Remix)

### ISSUE THREAD

**Issue by lancilloties** [KBVE/kbve#2085]
## **Music Suggestion Form**

YouTube Link: https://www.youtube.com/watch?v=OTYqOqkhyJU
Title: Wolfgang Lohr & Offbeat - Swing in Spring (Glenn Gatsby Remix)
Genre:electroswing

Hint: Only genres that are acceptable are: dnb, chillstep, lofihiphop, nujazz, electroswing, edm, rock, jrock, studybeats, anime

**Comment by h0lybyte** [comment]
Requested song was merged! Thanks!
