### ISSUE TITLE
[Bug] : [Kube] : Neuvector Failed with pending state.

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#2673]
**Describe the bug**

Looks like the Neuvector is stuck in pending, looking to attach a networking service.
The bug is similar to this [one](https://github.com/rancher/rancher/issues/45168).

As we talked about it earlier, it might be the `NodePort` or `ClusterIP` setting , we can review it later tonight.

**Comment by joshtek0** [comment]
Hypothesized that the lack of a loadbalancer endpoint available is the cause of this hangup.

```
kubectl get services -n cattle-neuvector-system
NAME                              TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
neuvector-service-webui           LoadBalancer   10.43.110.70    <pending>     8443:30697/TCP                  38h
neuvector-svc-admission-webhook   LoadBalancer   10.43.186.181   <pending>     443:32702/TCP                   38h
neuvector-svc-controller          ClusterIP      None            <none>        18300/TCP,18301/TCP,18301/UDP   38h
neuvector-svc-crd-webhook         ClusterIP      10.43.205.7     <none>        443/TCP                         38h
```

**Comment by h0lybyte** [comment]
We could switch the `LoadBalancer` type to a `ClusterIP` OR `NodePort`, both are the other two options.

This would be applied to the `neuvector-service-webui` and `neuvector-svc-admission-webhook` ?

**Comment by joshtek0** [comment]
Switched `LoadBalancer` to `ClusterIP` and re-deployed through `helm`. New status.

```
[Installed App:]
neuvector
Pending-Upgrade
Namespace: [cattle-neuvector-system]
```

**Comment by joshtek0** [comment]
Status changed after some time. Resolved.

```
Installed App:
neuvector
Deployed
```
