### ISSUE TITLE
[Concept] : Rare Icon Unity 6 LTS Upgrade

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#3147]
**Core Concept/Theory**

Simple ticket, we just need to upgrade the Unity 6 to LTS, which is just one minor version above the current instance.
We will do this during the unity session, but I am keeping this ticket as a means of tracking.

**Comment by JigSawPsycho** [comment]
Project has been updated to Unity LTS version 6000.0.26f1

**Comment by h0lybyte** [comment]
Okay closing this ticket out, that upgrade process looks like it went through perfectly.
