### ISSUE TITLE
[App] : [Saber] : Game Audio Implementation

### ISSUE THREAD

**Issue by pablowunderlich** [KBVE/kbve#344]
Game Audio where I would create sfx, design sound, create music, and implement all these assets using either FMOD or Wwise depending on developer preference. 

Assets:
- sound effects
- music (linear and interactive)
- music for cutscenes
- trailer music

Implementation:
- C# implementation using audio middleware such as Wwise of FMOD

**Comment by h0lybyte** [comment]
In reference to loading FMod for WebGL 
- https://www.fmod.com/docs/2.02/unity/platform-specifics.html

I am just double checking the license agreements when it comes to distribution.
Reference - https://qa.fmod.com/t/can-we-commit-the-fmod-api-to-our-integration-libraries-on-github/15751/6

**Comment by pablowunderlich** [comment]
Good to see FMOD supports webgl builds. As for the repo seems it's ok to use as far as there's an indication that FMOD libs are not free.
