### ISSUE TITLE
[Update] : [Kube] : RKE Version Upgrade from v1.30.4+rke2r1 to v1.31.3-rke2r1 & Rancher Version Upgrade from 2.9.1 to 2.9.4

### ISSUE THREAD

**Issue by joshtek0** [KBVE/kbve#3571]
**Describe the update**
We are planning to upgrade the RKE cluster to the latest stable version. The upgrade will include bug fixes, security patches, and new features. It will ensure that the system remains up-to-date and secure.

* * *
**References for update**
[Kubernetes changelog for the target version](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md)
[RKE upgrade documentation](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes)

* * *
**Security/Performance risks**
The upgrade process may introduce temporary instability, and there is a risk of breaking changes depending on the version. It is recommended to test the upgrade on a staging environment first and follow the Kubernetes upgrade documentation closely.

RISK: true

Risk Mitigation Strategy: create PVE backups for each node, will be used to restore the nodes while a new upgrade strategy is formulated in case of irrecoverable cluster failure relating to the upgrade process.

* * *
**Process Strategy**
The Rancher panel should allow us to push an update to RKE by editing the cluster configuration. Additional configuration for the upgrade automation can be applied to `cluster.yml` if needed.

**Comment by h0lybyte** [comment]
[Rancher Release Notes](https://github.com/rancher/rke/releases)

**Comment by h0lybyte** [comment]
INFO: starting new backup job: vzdump 235 --compress zstd --notes-template '{{guestname}}' --mode snapshot --node server --storage rpool-backup --remove 0 --notification-mode auto

^ from 235, 234, 233, 232, 231

**Comment by h0lybyte** [comment]
Everything looks fine from the change logs

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md#changelog-since-v1306

Nothing is breaking there.

**Comment by joshtek0** [comment]
Upgrade complete. RKE is now running version v1.31.3+rke2r1. To accomplish this, we has to edit the `cluster.yml` rather than upgradeing directly through the UI (past v1.30.7+rke2r1).

It is noteworthy that we found stable releases listed in [SUSE Documentation for Rancher](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/) rather than the [GitHub Releases shown for the Rancher project](https://github.com/rancher/rke2/releases).

Considering that the SUSE documentation cites the latest Rancher version to be 2.9.4, whereas the KBVE cluster is running 2.9.1, we are now looking into upgrading the Rancher version to 2.9.4 at this time.

**Comment by joshtek0** [comment]
![GeorgeWBushGIF](https://github.com/user-attachments/assets/8ba35bff-b7bb-4658-816c-5f36da146325)
