### ISSUE TITLE
[Concept] : Add support for Internal Error handling

### ISSUE THREAD

**Issue by artech-git** [KBVE/kbve#438]
**Core Concept/Theory**
Internal Error handling for the rust projects are mostly highly dispersed in a non standardized fashion which casuse severe inconsistency across multiple method calls ! 
```rust
fn method1() -> Result<String, Box<dyn ...>>
fn method1() -> Result<char, &'static str>>
```

* * *

**Alternative Ideas**

Maintaining a consistent API Result type for handling the errors across entire project and attaching trait behavior to the error type itself can make things much better in a long run 
one of a possible scenario for implementing this could be 

```rust
use std::panic::Location; 
use std::location::Backtrace; 

pub type ProcessResult<T> = std::result::Result<T, FragmentError>; 

#[derive(Debug)]
pub struct FragmentError { 
    error: ErrorsVariants,
    trace: Backtrace, 
}

impl<T> std::convert::From<T> for FragmentError
where T: Into<ErrorsVariants>  
{
    #[track_caller]
    fn from(val: T) -> FragmentError {
        let location = Location::caller(); 
        Self { 
            error: val.into(), 
            trace: location, 
        }
    }
}

#[derive(Debug, thiserror::Error, )]
pub enum ErrorsVariants { 
     #[error(" Some error message: {:0?}"]
     StringConvErr(#[from] ToStrError)
     ...
     ...
}
```

having a custom type for `pub type ProcessResult<T> = std::result::Result<T, FragmentError>`
allows repurposing the errors and utilizing the behaviour to be attached to it.

```rust
fn method1() -> ProcessResult<String>
fn method2() -> ProcessResult<Cow<'_, str>>
```

* * *

**Additional information**

we can also declare trait behavior on the type itself to be purpose elsewhere if we declare to be so ..

```rust
impl axum::IntoResponse for FragmentError { 
  fn to_response(self) -> impl IntoResponse {
        .....
  }
}
```

**Comment by h0lybyte** [comment]
Would we be using thiserror crate?

https://crates.io/crates/thiserror

**Comment by artech-git** [comment]
> Would we be using thiserror crate?
> 
> https://crates.io/crates/thiserror

yes, as it will enable to have highly maintainable code while scaling up the complexity of the error handling 
more details are linked here .. .  https://github.com/artech-git/kbve/commit/6b3944a43706b366f5452cea78b640f1aabf3a59

**Comment by h0lybyte** [comment]
You can split the patches up, maybe one patch would be for just adding the "this-error" to the project, another patch would be the creation of the "error.rs" and adding it into the lib.

**Comment by h0lybyte** [comment]
The other crate that I found was anyhow, which seems to be more application-specific, whereas thiserror seems to be more library-specific.
