### ISSUE TITLE
[Concept] : VM 230

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#719]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

VM 230

Issue ticket to help keep track of VM 230.

We had some issues with the QEMU / Bios but we were able to resolve it.

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

None yet.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

None yet.

* * *

**Additional information**
Add any other context or examples of this concept here.

None yet.

**Comment by Fudster** [comment]
Here is the specs of VM 20

 CPU usage 3.72% of 16 CPUs
Memory usage 49.29% (3.94 GiB of 8.00 GiB)
Hard drive size: 37GB of 64.00 GB

**Comment by h0lybyte** [comment]
I will set up an encrypted messaging system so that we can issue tickets without having any information leaked.

This will be under the the same issue, 719.

**Comment by h0lybyte** [comment]
The audio driver for the vm 230 is missing or broken, we can look into addressing and/or fixing this issue tomorrow morning.

I am thinking that it will be a simple fix because I had this issue in the past, its most likely basic human error.

**Comment by Fudster** [comment]
> The audio driver for the vm 230 is missing or broken, we can look into addressing and/or fixing this issue tomorrow morning.
> 
> I am thinking that it will be a simple fix because I had this issue in the past, its most likely basic human error.

This was fixed by https://www.oreilly.com/library/view/mastering-proxmox/9781788397605/09a8f5cd-4424-485d-9610-5fe6af288bd5.xhtml

**Comment by h0lybyte** [comment]
The audio crackling could be from a VAC Clock Difference, https://vac.muzychenko.net/en/manual/glossary.htm#ClockDifference

We could look into this on a later date because its not a major bug that we need to resolve right now.

**Comment by h0lybyte** [comment]
We need to add a way to backup the whole VM and then look into replacing it all with a more slim down version.

I am looking at Windows 10? Furthermore, we can also migrate the whole setup to a local machine, ideally within the next couple weeks. 

Moving this from a 6 down to a 1.

**Comment by Fudster** [comment]
I adjusted the ram to 12192MIB, Currently running 22 windows.

**Comment by h0lybyte** [comment]
Whats the uptime on the VM 230 ? @Fudster

**Comment by Fudster** [comment]
Requesting a Ubuntu machine with 4GB ram, 5 cores, 60GB HDD, for test casing the app if there's any bugs on linux

**Comment by h0lybyte** [comment]
We can close this out, as we have VM 230 functional for a month+ and no major issues.
