### ISSUE TITLE
[App] : [FishChip] : Common Bugs

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve#836]
**Describe the bug**

This is the collective bug report for the fishchip application before we get to the itch launch.

- [x] Monospace and Letter spacing for the FishGame
- [ ] Direction + Story Improvements, usually with hints.
- [x] WASD Movement
- [x] Instant retry with Shift or R
- [x] Object pooling for sandstorm
- [x] Track total score in web storage

**Comment by BChip** [comment]
Monospace and letter spacing fixed in #882

**Comment by BChip** [comment]
The following is now done. See https://github.com/KBVE/kbve/commit/a31936966fa99364857474dde8d138bef54ddff8

-  Instant retry with Shift or R
-  Object pooling for sandstorm
-  Track total score in web storage

**Comment by h0lybyte** [comment]
I am going to keep the totalScores as it is and then add a new function for inventory using nanostores.

This way we can keep track of the total score BUT also have a way to track the total amount of fish that is actively in the user's inventory.

**Comment by lancilloties** [comment]
@BChip How is this issue progressing?

**Comment by h0lybyte** [comment]
We can close this issue soon and merge it https://github.com/KBVE/kbve/issues/880 , which will also be closed in a bit and merged into a new ticket.
