### ISSUE TITLE
[Bug] Missing favicon & wrong copyright year on https://shop.kbve.com/

### ISSUE THREAD

**Issue by lancilloties** [KBVE/kbve#896]
**Describe the bug**
The favicon on kbve.com is missing on the https://shop.kbve.com/ & the wrong copyright is set on the pages.

* * *

**To Reproduce**
Go on https://shop.kbve.com/

* * *

**Expected behavior**
2024 as a copyright year & the favicon identical to kbve.com.

* * *

**Comment by h0lybyte** [comment]
That subdomain is just a place holder and I will close this ticket out.
 
 It can be part of the Merch ticket. https://github.com/KBVE/kbve/issues/837
